services:
  frontend:
    image: idealflowerr/frontend:1
    # 본인 도커허브에 맞게 수정.
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cnet

  backend:
    image: idealflowerr/backend:1
    # 본인 도커허브에 맞게 수정.
    networks:
      - cnet

networks:
  cnet:
    external: true
